-- Criação e seleção do banco de dados
CREATE DATABASE IF NOT EXISTS sistema_gestao_filas_agendamentos_publicos;
USE sistema_gestao_filas_agendamentos_publicos;

-- Remoção de tabelas existentes (se necessário)
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS agendamento;
DROP TABLE IF EXISTS lotacao;
DROP TABLE IF EXISTS oferece;
DROP TABLE IF EXISTS dependente;
DROP TABLE IF EXISTS cidadao;
DROP TABLE IF EXISTS funcionario;
DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS telefone;
DROP TABLE IF EXISTS pessoa;
DROP TABLE IF EXISTS unidade;
DROP TABLE IF EXISTS servico;
DROP TABLE IF EXISTS endereco;
SET FOREIGN_KEY_CHECKS = 1;

-- Criação das tabelas
CREATE TABLE endereco (
    ID_ENDERECO INT NOT NULL AUTO_INCREMENT,
    LOGRADOURO  VARCHAR(100) NOT NULL,
    CEP         VARCHAR(10)  NOT NULL,
    RUA         VARCHAR(100) NOT NULL,
    NUMERO      VARCHAR(10)  NOT NULL,
    PRIMARY KEY (ID_ENDERECO)
);

CREATE TABLE servico (
    ID_SERVICO  INT          NOT NULL AUTO_INCREMENT,
    NOME        VARCHAR(100) NOT NULL,
    TEMPO_MEDIO INT          NOT NULL,
    PRIMARY KEY (ID_SERVICO)
);

CREATE TABLE pessoa (
    CPF              VARCHAR(11)  NOT NULL,
    NOME             VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO  DATE         NOT NULL,
    ID_ENDERECO      INT          NOT NULL,
    PRIMARY KEY (CPF),
    FOREIGN KEY (ID_ENDERECO) REFERENCES endereco(ID_ENDERECO)
);

CREATE TABLE usuario (
    ID_PESSOA   VARCHAR(11)  NOT NULL,
    EMAIL       VARCHAR(100) NOT NULL UNIQUE,
    SENHA_HASH  VARCHAR(150) NOT NULL,
    PERFIL      ENUM('SEC','GES','PRO','CID') NOT NULL,
    PRIMARY KEY (ID_PESSOA),
    FOREIGN KEY (ID_PESSOA) REFERENCES pessoa(CPF)
);

CREATE TABLE telefone (
    ID_PESSOA        VARCHAR(11) NOT NULL,
    COD_TELEFONE     INT         NOT NULL,
    NUMERO_TELEFONE  VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_PESSOA, COD_TELEFONE),
    FOREIGN KEY (ID_PESSOA) REFERENCES pessoa(CPF)
);

CREATE TABLE funcionario (
    ID_PESSOA  VARCHAR(11) NOT NULL,
    MATRICULA  VARCHAR(20) NOT NULL UNIQUE,
    CARGO      VARCHAR(50) NOT NULL,
    ADMISSAO   DATE        NOT NULL,
    PRIMARY KEY (ID_PESSOA),
    FOREIGN KEY (ID_PESSOA) REFERENCES pessoa(CPF)
);

CREATE TABLE cidadao (
    ID_PESSOA   VARCHAR(11) NOT NULL,
    CARTAO_SUS  VARCHAR(20) NOT NULL UNIQUE,
    NIS         VARCHAR(20) NOT NULL UNIQUE,
    PRIMARY KEY (ID_PESSOA),
    FOREIGN KEY (ID_PESSOA) REFERENCES pessoa(CPF)
);

CREATE TABLE dependente (
    ID_PESSOA      VARCHAR(11) NOT NULL,
    ID_RESPONSAVEL VARCHAR(11) NOT NULL,
    VIGENCIA       DATE        NOT NULL,
    PARENTESCO     VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_PESSOA, ID_RESPONSAVEL),
    FOREIGN KEY (ID_PESSOA)      REFERENCES pessoa(CPF),
    FOREIGN KEY (ID_RESPONSAVEL) REFERENCES pessoa(CPF)
);

CREATE TABLE unidade (
    ID_UNIDADE  INT          NOT NULL AUTO_INCREMENT,
    NOME        VARCHAR(100) NOT NULL,
    TIPO        VARCHAR(50)  NOT NULL,
    ID_ENDERECO INT          NOT NULL,
    PRIMARY KEY (ID_UNIDADE),
    FOREIGN KEY (ID_ENDERECO) REFERENCES endereco(ID_ENDERECO)
);

CREATE TABLE agendamento (
    ID_AGENDAMENTO           INT          NOT NULL AUTO_INCREMENT,
    OBSERVACAO               VARCHAR(255),
    DATA                     DATE         NOT NULL,
    HORA                     TIME         NOT NULL,
    DATA_INICIO_REALIZADO    DATE         NULL,
    DATA_FINAL_REALIZADO     DATE         NULL,
    HORARIO_REALIZADO        TIME         NULL,
    ID_FUNCIONARIO_REALIZADO VARCHAR(11)  NULL,
    ID_UNIDADE_SEDIADA       INT          NOT NULL,
    ID_CIDADAO_SOLICITADO    VARCHAR(11)  NOT NULL,
    ID_SERVICO_REFERENTE     INT          NOT NULL,
    STATUS_AGENDAMENTO       ENUM('PENDENTE','CONFIRMADO','CANCELADO','REALIZADO') NOT NULL,
    PRIORIDADE               INT,
    NOTIFICACAO              TINYINT(1)   DEFAULT 0,
    PRIMARY KEY (ID_AGENDAMENTO),
    FOREIGN KEY (ID_FUNCIONARIO_REALIZADO) REFERENCES funcionario(ID_PESSOA),
    FOREIGN KEY (ID_UNIDADE_SEDIADA)       REFERENCES unidade(ID_UNIDADE),
    FOREIGN KEY (ID_CIDADAO_SOLICITADO)    REFERENCES cidadao(ID_PESSOA),
    FOREIGN KEY (ID_SERVICO_REFERENTE)     REFERENCES servico(ID_SERVICO)
);

CREATE TABLE lotacao (
    ID_FUNCIONARIO  VARCHAR(11)  NOT NULL,
    ID_UNIDADE      INT          NOT NULL,
    DATA_INICIO     DATE         NOT NULL,
    DATA_FINAL      DATE         NOT NULL,
    HORARIOS        VARCHAR(100),
    PRIMARY KEY (ID_FUNCIONARIO, ID_UNIDADE),
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES funcionario(ID_PESSOA),
    FOREIGN KEY (ID_UNIDADE)     REFERENCES unidade(ID_UNIDADE)
);

CREATE TABLE oferece (
    ID_UNIDADE  INT         NOT NULL,
    ID_SERVICO  INT         NOT NULL,
    DIA_SEMANA  ENUM('SEG','TER','QUA','QUI','SEX','SAB','DOM') NOT NULL,
    HORA_INICIO TIME        NOT NULL,
    HORA_FINAL  TIME        NOT NULL,
    VAGAS       INT         NOT NULL,
    PRIMARY KEY (ID_UNIDADE, ID_SERVICO),
    FOREIGN KEY (ID_UNIDADE) REFERENCES unidade(ID_UNIDADE),
    FOREIGN KEY (ID_SERVICO) REFERENCES servico(ID_SERVICO)
);